---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor-deployment  # Nome ajustado sem pontos
  labels:
    app: conversor
spec:
  replicas: 5
  selector:
    matchLabels:
      app: conversor
  template:
    metadata:
      labels:
        app: conversor
    spec: 
      containers:
      - name: conversor
        image: us-central1-docker.pkg.dev/GCP_PROJECT_ID/image-repo/conversor-peso:IMAGE_TAG
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conversor
  labels:
    app: conversor
spec:
  selector:
    app: conversor
  ports:
  - protocol: TCP
    port: 80          # Porta exposta no serviço
    targetPort: 8080  # Porta do contêiner
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conversor-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: conversor
            port:
              number: 80  # Deve corresponder à porta exposta no Service
