name: Deploy to Kubernetes
on:
  push:
    branches:
      - main
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
    - name: install gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        install_components: 'gke-gcloud-auth-plugin'  
        export_default_credentials: true

    - name: Build and push Docker image
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/$GCP_PROJECT_ID/image-repo/conversor-peso:${{ github.sha }} .
        docker push us-central1-docker.pkg.dev/$GCP_PROJECT_ID/image-repo/conversor-peso:${{ github.sha }}
   
    - name: deploy to Kubernetes
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud container clusters get-credentials cluster-1-kubernetes --region us-central1-c --project ${{ secrets.GCP_PROJECT_ID }}
        sed -i "s/GCP_PROJECT_ID/${{ secrets.GCP_PROJECT_ID }}/g" resources.yaml
        sed -i "s|IMAGE_TAG|${{ github.sha }}|g" resources.yaml
        kubectl apply -f resources.yaml
        